# 1. Project Identity
# RULE: This must use underscores (_), NOT hyphens (-).
name: 'dbt_cert_prep'
version: '1.0.0'
config-version: 2

# 2. Connection Profile
profile: 'default'

# 3. Directory Settings
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# 4. Model Architecture
models:
  dbt_cert_prep:      # <--- This MUST match the 'name' on line 3
    # Global Default
    +materialized: view

    staging:
      # Staging Layer = Views
      +materialized: view

    marts:
      # Marts Layer = Tables
      +materialized: table